import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms — Readr",
  description: "Ground rules for using Readr.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 pb-24 pt-4 text-ink">
      <header className="mb-10 border-b border-rule-2 pb-8">
        <p className="text-kicker font-semibold uppercase tracking-[0.18em] text-ink-3">
          terms of service
        </p>
        <h1 className="mt-2 font-serif text-h2 font-semibold tracking-[-0.01em]">
          a few ground rules.
        </h1>
        <p className="mt-3 text-prose text-ink-2">
          Last updated May 15, 2026. Readr is a small, invite-only reading app.
          By signing in you agree to the terms below. If you don't agree, please
          don't use it.
        </p>
      </header>

      <article className="space-y-10 text-prose text-ink-2 leading-relaxed">
        <Section title="invite-only access">
          <p>
            Readr does not have public sign-ups. Accounts are granted by
            invitation to a specific email address. Access may be revoked at any
            time, for any reason, without notice.
          </p>
        </Section>

        <Section title="what you upload">
          <p>
            You are responsible for the EPUB files you upload. Only upload
            content that you own, have a license for, or that is otherwise in
            the public domain. Don't upload anything illegal, infringing, or
            harmful.
          </p>
          <p>
            Your uploads are stored privately for your own use. You retain
            ownership of anything you upload; Readr just stores and serves it
            back to you.
          </p>
        </Section>

        <Section title="the AI companion">
          <p>
            The chat feature passes your prompt and relevant chapter context to
            a third-party language model. Responses are generated by that model.
            They can be wrong, incomplete, biased, or misleading, and should not
            be relied on for anything important.
          </p>
          <p>
            Don't use Readr's AI chat to seek medical, legal, financial, or
            other professional advice. If you do, that's on you.
          </p>
        </Section>

        <Section title="no warranty, no uptime">
          <p>
            Readr is provided as-is, without warranties of any kind. There is no
            uptime guarantee. The service may change, be paused, or be shut down
            at any time.
          </p>
        </Section>

        <Section title="acceptable use">
          <p>
            Don't try to break Readr, abuse its infrastructure, attempt to
            access other users' data, or use it to generate or store unlawful
            content. Accounts found doing so will be removed.
          </p>
        </Section>

        <Section title="liability">
          <p>
            To the maximum extent allowed by law, Readr and its operator are not
            liable for any indirect, incidental, consequential, or punitive
            damages arising from your use of the service. Your only remedy if
            you're unhappy is to stop using it.
          </p>
        </Section>

        <Section title="changes">
          <p>
            If these terms change in a material way, you'll see a note on this
            page with a new "last updated" date. Continued use after a change
            counts as acceptance.
          </p>
        </Section>

        <Section title="contact">
          <p>
            Questions or concerns:{" "}
            <a
              className="text-accent underline underline-offset-4 hover:no-underline"
              href="mailto:srijakonjarla@gmail.com"
            >
              srijakonjarla@gmail.com
            </a>
            .
          </p>
        </Section>
      </article>

      <footer className="mt-16 flex items-center justify-between border-t border-rule-2 pt-6 text-kicker text-ink-3">
        <Link href="/privacy" className="hover:text-ink">
          ← privacy
        </Link>
        <Link href="/" className="hover:text-ink">
          back →
        </Link>
      </footer>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h2 className="font-serif text-h4 font-semibold tracking-[-0.01em] text-ink">
        {title}
      </h2>
      {children}
    </section>
  );
}
